# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
export COMMON_DOTFILES=$DOTFILES/ohmyzsh-common
export PLATFORM_DOTFILES=$DOTFILES/ohmyzsh-mac

# Let the magic begin
source $COMMON_DOTFILES/zshrc
#above will also source $PLATFORM_DOTFILES ;)

# my aliases
x=$(sysctl -n hw.ncpu)

PATH=/usr/local/bin:/usr/local/sbin:$PATH # Add /usr/local to PATH

PATH=$PATH:/usr/local/opt/go/libexec/bin # Go stuff
export GOPATH=$HOME/code/go

PATH=/export/apps/python/2.7/bin:$PATH # python stuff

[[ `hostname` = "vimehta-mn1" ]] && test -z "$(netstat -atnp tcp | grep -i "listen" | grep "\.11000")" && (listen_yubikey &)
[[ `hostname` = "vimehta-mn1" ]] && test -z "$(netstat -atnp tcp | grep -i "listen" | grep "\.12000")" && (listen_clipboard &)
