# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
export COMMON_DOTFILES=$DOTFILES/ohmyzsh-common
export PLATFORM_DOTFILES=$DOTFILES/ohmyzsh-mac

# Let the magic begin
source $COMMON_DOTFILES/zshrc
#above will also source $PLATFORM_DOTFILES ;)

# my aliases
x=$(sysctl -n hw.ncpu)

PATH=/usr/local/bin:/usr/local/sbin:$PATH # Add /usr/local to PATH

[[ `hostname` = "vimehta-mn1" ]] && test -z "$(netstat -atnp tcp | grep -i "listen" | grep "\.11000")" && (listen_yubikey &)
