# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
export COMMON_DOTFILES=$DOTFILES/common/ohmyzsh
export PLATFORM_DOTFILES=$DOTFILES/arch/ohmyzsh

# Let the magic begin
source $COMMON_DOTFILES/zshrc
#above will also source $PLATFORM_DOTFILES ;)

# my aliases
x=$(cat /proc/cpuinfo|grep -c processor)
