# If not running interactively, do not do anything
[[ $- != *i* ]] && return
[[ $TERM != screen* ]] && test -z "$TMUX" && (tmux attach || tmux new-session) && exit

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.dotfiles/ohmyzsh-arch

# Let the magic begin
source $ZSH/../ohmyzsh-common/zshrc

# my aliases
alias clip='xclip -selection c'
alias ksr='source $HOME/kde/bashrc; cs'
x=$(cat /proc/cpuinfo|grep -c processor)
