# If not running interactively, do not do anything
[[ $- != *i* ]] && return
[[ $TERM != screen* ]] && [[ "$TERM_PROGRAM" != vscode ]] && test -z "$TMUX" && (tmux attach || tmux new-session) && exit

# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
export COMMON_DOTFILES=$DOTFILES/common/ohmyzsh
export PLATFORM_DOTFILES=$DOTFILES/rhel/ohmyzsh

# Let the magic begin
source $COMMON_DOTFILES/zshrc
#above will also source $PLATFORM_DOTFILES ;)
