# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
export COMMON_DOTFILES=$DOTFILES/common/ohmyzsh
export PLATFORM_DOTFILES=$DOTFILES/mac/ohmyzsh

# Let the magic begin
source $COMMON_DOTFILES/zshrc
#above will also source $PLATFORM_DOTFILES ;)

# my aliases
x=$(sysctl -n hw.ncpu)

test -d /usr/local/sbin && export PATH=$PATH:/usr/local/sbin # Add /usr/local to PATH

test -d /export/apps/python/2.7/bin && export PATH=/export/apps/python/2.7/bin:$PATH # python stuff
