# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
export COMMON_DOTFILES=$DOTFILES/common/ohmyzsh
export PLATFORM_DOTFILES=$DOTFILES/mac/ohmyzsh

# Let the magic begin
source $COMMON_DOTFILES/zshrc
#above will also source $PLATFORM_DOTFILES ;)

# my aliases
x=$(sysctl -n hw.ncpu)

PATH=/usr/local/bin:/usr/local/sbin:$PATH # Add /usr/local to PATH

PATH=/export/apps/python/2.7/bin:$PATH # python stuff

[[ `hostname` = "vimehta-mn1" ]] && test -z "$(netstat -atnp tcp | grep -i "listen" | grep "\.12000")" && (listen_clipboard &)
