# aliases
alias db='docker build -t'
alias dl='docker pull'
alias dim='docker images'
alias dimclean='docker rmi `docker images | grep "<none>" | awk "{print \$3}"`'
alias drmi='docker rmi'
alias drn='docker run --rm -it'
alias dps='docker ps -a  --format "table {{.Names}}\t{{.Command}}\t{{.Status}}\t{{.Ports}}"'
alias de='docker exec -it'
alias dlf='docker logs -f'
alias din='docker inspect'
alias drm='docker rm'
