# Load all of the config files in ~/oh-my-zsh that end in .zsh
fpath=($PLATFORM_DOTFILES/completion $COMMON_DOTFILES/completion $fpath)
for config_file ($COMMON_DOTFILES/*.zsh) source $config_file
for config_file ($PLATFORM_DOTFILES/*.zsh) source $config_file

# Customize to your needs...
export EDITOR=vim
test -n "$TMUX" && export TERM="screen-256color"

# Put ~/bin in PATH for dropping random binaries
test -d $HOME/bin && export PATH=$PATH:$HOME/bin
